Tracker:AddLocations("locations/Astral Plane (Location).json")
Tracker:AddLocations("locations/Collectibles.json")
Tracker:AddLocations("locations/Containment Sector.json")
Tracker:AddLocations("locations/Executive Sector.json")
Tracker:AddLocations("locations/Maintenance Sector.json")
Tracker:AddLocations("locations/Oceanview Motel (Location).json")
Tracker:AddLocations("locations/Research Sector.json")
Tracker:AddLocations("locations/Sectors.json")
Tracker:AddLocations("locations/Side Missions.json")
Tracker:AddLocations("locations/Story Missions.json")
